name: Generate Correct Lockfile

on:
  workflow_dispatch:

jobs:
  build-lockfile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Remove old lockfile
        run: rm -f package-lock.json

      - name: Install dependencies & generate new lockfile
        run: npm install

      - name: Upload new package-lock.json
        uses: actions/upload-artifact@v4
        with:
          name: package-lock.json
          path: package-lock.json
